project:
  type: website

website:
  title: "Valuing Nature NREM 691"
  search: true
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: Contingent Valuation
      - href: dce.qmd
        text: Discrete Choice
      - href: hd.qmd
        text: Hedonic
      - href: tc.qmd
        text: Travel Cost

    tools:
      - icon: youtube
        href: https://www.youtube.com/@Prof.Iguana
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/loweas/ValuingNature
          - text: Report a Bug
            href:  https://github.com/loweas/ValuingNature/issues

format:
  html:
    theme: cosmo
    toc: true
